name: Deploy Pelican Site

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pelican[markdown]" ghp-import

      - name: Build site
        run: |
          pelican content -o output -s pelicanconf.py

      - name: Deploy to GitHub Pages
        run: |
          ghp-import output -b gh-pages
          git push origin gh-pages --force
          ghp-import output -b gh-blog
          git push origin gh-blog --force
